columns:
         
  season: category      
  yr: category          
  mnth: category         
  hr: category         
  holiday: category       
  weekday: category       
  
  weathersit: category     
  temp : float          
      
  windspeed: float    
  casual: int         
  registered : int    
  cnt: int 

numerical_columns:                  
  - temp          
          
  - windspeed     
  - casual        
  - registered            

categorical_columns:
  - season
  - yr 
  - mnth          
  - hr            
  - holiday       
  - weekday       
  
  - weathersit
  
target_column: 
  - cnt

domain_value:
  season:
    - 1
    - 2
    - 3
    - 4
  yr:
    - 0
    - 1
  mnth:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  hr:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
  holiday:
    - 0
    - 1
  weekday:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6

  weathersit:
    - 1
    - 2
    - 3
    - 4
    
  